identidock:
  build: . 
  links:
    - dnmonster
    - redis
  ports:
   - "5000:5000"
  environment:
    ENV: DEV 
  volumes:
    - ./app:/app
     

dnmonster:
   image: amouat/dnmonster:1.0

redis:
    image: redis:3.0
  
 
